version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - TOKEN=${token}
      - MONGOURI=${mongouri}
      - TRAININGDATA=${trainingdata}
    ports:
      - "3000:3000"